[project]
name = "multisensor-splat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nino Menzel", email = "nino.menzel@inform-software.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "open3d>=0.20.0",
    "opencv-python>=5.0.0.93",
    "pykitti>=0.3.1",
    "scipy>=1.18.1",
]

[project.scripts]
multisensor-splat = "multisensor_splat:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
]
